version: '3.7'

services:
    mongo:
        image: mongo:5
        container_name: mongo
        ports:
            - 27017:27017
    mongo-express:
        image: mongo-express:0.54
        container_name: mongo-express
        ports:
            - 8081:8081
        environment:
            ME_CONFIG_MONGODB_SERVER: mongo
